/* eslint-disable @next/next/no-img-element */
import Layout from "~/layouts/default";
import Link from "next/link";
import { ArrowRightIcon, ClockIcon } from "@heroicons/react/24/solid";

// construct the meta data for the page
const metaData = {
  title: "Browser Extension",
  description:
    "Explore the decentralized Solana web though the power of .sol domains and IPFS.",
};

export default function Page() {
  return (
    <Layout seo={metaData} className="md:space-y-16">
      <div className="container col-span-2 py-14 mx-auto space-y-8 max-w-2xl text-center">
        <h1 className="text-5xl font-bold">
          Explore the Decentralized
          <br /> Solana Web
        </h1>

        <p className="mx-auto text-xl text-gray-500">
          Browse .sol domains and IPFS websites like web2
        </p>

        <div className="flex justify-center space-x-5">
          {/* <Link href="/extension">
            <a className="block w-min btn-flex disabled">
              <span>Chrome WebStore Coming Soon</span>
              <ClockIcon className="icon-sm" />
            </a>
          </Link> */}

          <Link href="https://github.com/solfate/extension">
            <a
              className="block w-min btn-flex btn-indigo"
              target="_blank"
              rel="noreferrer"
            >
              <span>View on GitHub</span>
              <ArrowRightIcon className="icon-sm" />
            </a>
          </Link>
        </div>

        <p className="grid gap-3 text-center md:gap-8 md:grid-cols-2">
          <Link href="https://youtu.be/J11ybP3nZE8">
            <a className="link" target="_blank" rel="noreferrer">
              <span>Watch a Demo Video</span>
            </a>
          </Link>

          <Link href="https://youtu.be/1Y9wEsJ8_j0">
            <a className="link" target="_blank" rel="noreferrer">
              <span>How to Manually Install</span>
            </a>
          </Link>
        </p>
      </div>

      <section className="p-8 bg-white">
        <section className="container grid gap-12 md:gap-8 lg:gap-5 md:grid-cols-2 lg:grid-cols-4">
          <div className="space-y-3 md:col-span-2 md:mb-14 lg:mb-0 md:px-24 lg:px-0">
            <h3 className="pl-4 text-2xl font-bold border-l-4 border-indigo-500">
              Solana Profile Pages
            </h3>
            <p className="text-lg text-gray-500">
              Autogenerated &quot;link in bio&quot; style landing pages for
              every <i>.sol</i> domain. All of the data pulled directly off the
              blockchain using the Solana Name Service and IPFS.
            </p>
            {/* <Link href="/extension">
						<a className="block w-min btn btn-indigo">
							<span>View Example Profile Page</span>
							<ArrowRightIcon className="icon-sm" />
						</a>
					</Link> */}
          </div>

          <div className="space-y-4 md:col-span-1">
            <h2 className="pl-4 text-2xl font-bold border-l-4 border-indigo-500">
              Resolve .sol Domains
            </h2>
            <p className="text-gray-500">
              Quickly resolves any <i>.sol</i> domain to its registered wallet
              address using the Solana Name Service (SNS).
            </p>

            {/* <a href="" className="text-lg tracking-wide link flexer">
						<span className="">Learn more</span>
						<ArrowRightIcon className="icon-sm" />
					</a> */}
          </div>
          <div className="space-y-4 md:col-span-1">
            <h2 className="pl-4 text-2xl font-bold border-l-4 border-indigo-500">
              IPFS Explorer
            </h2>
            <p className="text-gray-500">
              Easily browse pages, image collections, and other files uploaded
              to the InterPlanetary File System (IPFS).
            </p>

            {/* <a href="" className="text-lg tracking-wide link flexer">
						<span className="">Learn more</span>
						<ArrowRightIcon className="icon-sm" />
					</a> */}
          </div>
        </section>
      </section>
    </Layout>
  );
}
